// The published-build snapshot bound to the committed data: what each update
// channel is serving right now, per feature, generated by
// scripts/generate-channel-manifests.mjs from the live Sparkle appcast and the
// manifest at each build's git tag. The Modules page reads the trunk-head
// manifest for "what would ship"; this is "what did".
import snapshot from "../data/channel-manifests.json";
import {
  presenceIn,
  publishedChannelOrder,
  type ChannelSnapshot,
  type PublishedChannel,
  type PublishedChannelKey,
  type PublishedPresence
} from "./channel-presence";

// The JSON import is typed from the file's literal shape (optional keys per
// channel), so it has to go through unknown to the declared contract.
export const channelSnapshot = snapshot as unknown as ChannelSnapshot;

export function publishedChannel(key: PublishedChannelKey): PublishedChannel {
  const channel = channelSnapshot.channels.find((candidate) => candidate.key === key);
  if (!channel) throw new Error(`channel snapshot has no ${JSON.stringify(key)} channel — run npm run sync:channels`);
  return channel;
}

export function publishedChannels(): PublishedChannel[] {
  return publishedChannelOrder.map((key) => publishedChannel(key));
}

export function publishedPresence(featureId: string): PublishedPresence {
  return presenceIn(channelSnapshot, featureId);
}
